local TR_Manager = require("resurrected_modpack.manager")
ConsistentTears = TR_Manager:RegisterMod("Consistent Tear Costumes", 1)

local mod = ConsistentTears
local itemConfig = Isaac.GetItemConfig()
local game = Game()

----SCHEDULER (Stolen from Fiend Folio)
DelayedFuncs = {}
local function RunUpdates(tab)
  	for i = #tab, 1, -1 do
    		local f = tab[i]
    		f.Delay = f.Delay - 1
    		if f.Delay <= 0 then
      			f.Func()
      			table.remove(tab, i)
    		end
  	end
end
function mod:ScheduleForUpdate(foo, delay, callback, noCancelOnNewRoom)
  	callback = callback or ModCallbacks.MC_POST_UPDATE
  	if not DelayedFuncs[callback] then
    		DelayedFuncs[callback] = {}
    		mod:AddCallback(callback, function()
    		    RunUpdates(DelayedFuncs[callback])
    		end)
  	end
  	table.insert(DelayedFuncs[callback], { Func = foo, Delay = delay or 0, NoCancel = noCancelOnNewRoom })
end
mod:AddPriorityCallback(ModCallbacks.MC_POST_NEW_ROOM, CallbackPriority.IMPORTANT, function()
  	for callback, tab in pairs(DelayedFuncs) do
    		for i = #tab, 1, -1 do
      			local f = tab[i]
      			if not f.NoCancel then
                table.remove(tab, i)
      			end
    		end
  	end
end)

--Stolen from... I forgor. Samael?
function mod.GetPlayers()
  local players = {}
  for i=0, game:GetNumPlayers()-1 do
    local player = game:GetPlayer(i)
    if player and player:Exists() then
      players[i] = player
    end
  end
  return players
end

--Stolen from RealexTea's genius brain
mod.SkinColorToPostfix = {
[SkinColor.SKIN_PINK] = "",
[SkinColor.SKIN_WHITE] = "_white",
[SkinColor.SKIN_BLACK] = "_black",
[SkinColor.SKIN_BLUE] = "_blue",
[SkinColor.SKIN_RED] = "_red",
[SkinColor.SKIN_GREEN] = "_green",
[SkinColor.SKIN_GREY] = "_grey"
}

--If you want to add support of this mod to yours you can just
--ConsistentTears.Characters[ID_OF_YOUR_CHARACTER] = "costumes_tears_red"
--(or  "costumes_tears_redb" depending on the color you want)
mod.Characters = {
[PlayerType.PLAYER_LAZARUS2] = "costumes_tears_red",
[PlayerType.PLAYER_LILITH] = "costumes_tears_redb",
[PlayerType.PLAYER_ESAU]  = "costumes_tears_red",
--Originally I wanted to make Tainted ??? but he already has costumes of the regular one and I'm too tired to figure shit out
--[PlayerType.PLAYER_BLUEBABY_B] = "costumes_tears_poop",
[PlayerType.PLAYER_EVE_B] = "costumes_tears_black",
[PlayerType.PLAYER_LILITH_B] = "costumes_tears_redb",
[PlayerType.PLAYER_BETHANY_B] = "costumes_tears_redb",
[PlayerType.PLAYER_LAZARUS2_B] = "costumes_tears_redb",
}

function mod:GetCostumePrefix(p)
  local prefix = false
  local characterBased = mod.Characters[p:GetPlayerType()]
  if characterBased then
    prefix = characterBased
  else
    if p:HasCollectible(CollectibleType.COLLECTIBLE_STIGMATA) then
      prefix = "costumes_tears_redb"
    end
    if p:HasCollectible(CollectibleType.COLLECTIBLE_POP) or p:HasCollectible(CollectibleType.COLLECTIBLE_HAEMOLACRIA) then
      prefix = "costumes_tears_red"
    end
  end
  
  if prefix then
    return "gfx/characters/" .. prefix .. "/"
  else
    return false
  end
end

--Autogenerated
mod.ItemCostumes = {
[1] = {pngPath = "costume_058_sadonion"},
[2] = {pngPath = "costume_029_theinnereye"},
[3] = {pngPath = "costume_065_spoonbender", hasSkinAlt = true},
[4] = {pngPath = "costume_037_maxshead", hasSkinAlt = true},
[5] = {pngPath = "costume_047_myreflection"},
[13] = {pngPath = "costume_071_virus", hasSkinAlt = true},
[14] = {pngPath = "costume_056_roidrage", hasSkinAlt = true},
[55] = {pngPath = "costume_040_momseye", hasSkinAlt = true},
[62] = {pngPath = "costume_021_charmofthevampire", hasSkinAlt = true},
[132] = {pngPath = "costume_033_lumpofcoal"},
[140] = {pngPath = "costume_082_bobscurse"},
[151] = {pngPath = "costume_102_mulligan", hasSkinAlt = true},
[153] = {pngPath = "costume_103_mutantspider"},
[154] = {pngPath = "costume_087_chemicalpeel", hasSkinAlt = true},
[169] = {pngPath = "costume_106_polyphemus", hasSkinAlt = true},
[192] = {pngPath = "costume_065_spoonbender", hasSkinAlt = true}, --CAUTION: ACTIVE ITEM
[193] = {pngPath = "costume_098_meat", hasSkinAlt = true},
[203] = {pngPath = "costume_203_humblingbundle", hasSkinAlt = true},
[213] = {pngPath = "costume_213_lostcontact"},
[224] = {pngPath = "costume_224_crickets body"},
[228] = {pngPath = "moms perfume"},
[248] = {pngPath = "costume_248_hivemind", extraCostume = {anm2Path = "248_hive mind", pngPath = "costume_hive mind (body)"}},
[258] = {pngPath = "costume_258_missingno"},
[299] = {pngPath = "costume_235_taurus", hasSkinAlt = true},
[304] = {pngPath = "costume_304_libra_head", hasSkinAlt = true, extraCostume = {anm2Path = "304_libra", pngPath = "costume_304_libra_body", hasSkinAlt = true}},
[305] = {pngPath = "costume_305_scorpio", hasSkinAlt = true},
[307] = {pngPath = "costume_307_capricorn"},
--[308] = {pngPath = "costume_308_aquarius", isBody = true}, --Trail from aquarius never becomes red! Oh well.
[309] = {pngPath = "costume_309_pisces_head", hasSkinAlt = true, extraCostume = {anm2Path = "309_pisces", pngPath = "costume_309_pisces_body", hasSkinAlt = true}},
[317] = {pngPath = "costume_305_scorpio", hasSkinAlt = true},
[341] = {pngPath = "Costume_341_TornPhoto", hasSkinAlt = true},
[342] = {pngPath = "costume_342_bluecap", hasSkinAlt = true},
[368] = {pngPath = "Costume_368_Epiphora"},
[379] = {pngPath = "costume_379_pupuladuplex"},
[457] = {pngPath = "Costume_457_ConeHead", hasSkinAlt = true},
[461] = {pngPath = "Costume_461_Parasitoid", hasSkinAlt = true},
[495] = {pngPath = "Costume_495_GhostPepper"},
[499] = {pngPath = "Costume_499_Eucharist"},
[513] = {pngPath = "costume_513_Bozo"},
[525] = {pngPath = "Costume_525_Leprosy", hasSkinAlt = true},
[532] = {pngPath = "costume_532_lachryphagy", hasSkinAlt = true},
[547] = {pngPath = "costume_547_divorcepapers"},
[554] = {pngPath = "costume_001x_2spooky", extraCostume = {anm2Path = "001x_2Spooky", pngPath = "costume_001x_2spooky_body"}},
[562] = {pngPath = "costume_009x_rockbottom", hasSkinAlt = true},
[564] = {pngPath = "costume_011x_soap", hasSkinAlt = true},
[589] = {pngPath = "costume_036x_luna"},
[591] = {pngPath = "costume_038x_venus", hasSkinAlt = true},
[594] = {pngPath = "costume_041x_jupiter", hasSkinAlt = true},
[597] = {pngPath = "costume_044x_neptunus", extraCostume = {anm2Path = "044x_Neptunus", pngPath = "costume_044x_neptunus_body"}},
[598] = {pngPath = "costume_045x_pluto", hasSkinAlt = true},
[600] = {pngPath = "costume_047x_eyedrops"},
--[625] = {pngPath = "big_isaac", hasSkinAlt = true, extraCostume = {anm2Path = "big_isaac", pngPath = "big_isaac", hasSkinAlt = true}}, --CAUTION: ACTIVE ITEM
[637] = {pngPath = "costume_084x_knockout", hasSkinAlt = true},
[677] = {pngPath = "Character_012_TheLost", isBody = true},
[688] = {pngPath = "costume_045x_pluto", hasSkinAlt = true},
[704] = {pngPath = "costume_704_berserk", hasSkinAlt = true}, --CAUTION: ACTIVE ITEM
}

mod.NullCostumes = {
[NullItemID.ID_OVERDOSE] = {pngPath = "x_overdose", hasSkinAlt = true}
}

mod.PillToNull = {
[PillEffect.PILLEFFECT_ADDICTED] = NullItemID.ID_OVERDOSE
}

function mod:ReplaceItemCostume(p, id, isNull)
  local prefix = mod:GetCostumePrefix(p)
  local costumeData = mod.ItemCostumes[id]
  local config = itemConfig:GetCollectible(id)
  
  if isNull then
    costumeData = mod.NullCostumes[id]
    config = itemConfig:GetNullItem(id)
  end
  
  local path = prefix .. costumeData.pngPath
  if costumeData.hasSkinAlt then
    if costumeData.isBody then
      path = path .. mod.SkinColorToPostfix[p:GetBodyColor()]
    else
      path = path .. mod.SkinColorToPostfix[p:GetHeadColor()]
    end
  end
  path = path .. ".png"
  p:ReplaceCostumeSprite(config, path, 0)
  
  if costumeData.extraCostume then
    local extraCostume = Isaac.GetCostumeIdByPath("gfx/characters/bugfix/" .. costumeData.extraCostume.anm2Path .. ".anm2")
    p:AddNullCostume(extraCostume)
    local extraPath = prefix .. costumeData.extraCostume.pngPath
    if costumeData.extraCostume.hasSkinAlt then
      extraPath = extraPath .. mod.SkinColorToPostfix[p:GetBodyColor()]
    end
    extraPath = extraPath .. ".png"
    p:ReplaceCostumeSprite(itemConfig:GetNullItem(extraCostume), extraPath, 0)
    
    local d = p:GetData()
    if not d.ConsistentTearsExtra then d.ConsistentTearsExtra = {} end
    table.insert(d.ConsistentTearsExtra, id)
  end
end

function mod:UpdateCostumes(p)
  for key, costume in pairs(mod.ItemCostumes) do
    if p:HasCollectible(key, true) then
      mod:ReplaceItemCostume(p, key)
    end
  end

  local extraCostumes = p:GetData().ConsistentTearsExtra or {}
  for key = #extraCostumes, 1, -1 do
    if not p:HasCollectible(extraCostumes[key], true) then
      local costume = mod.ItemCostumes[extraCostumes[key]].extraCostume
      p:TryRemoveNullCostume("bugfix" .. costume.anm2Path .. ".anm2")
      table.remove(p:GetData().ConsistentTearsExtra, key)
    end
  end
end

mod:AddCallback(ModCallbacks.MC_POST_PEFFECT_UPDATE, function(_, p)
  local collectibleCount = p:GetCollectibleCount()
  local oldCount = p:GetData().ConsistentTearsCollectibleCount or 0
  if collectibleCount ~= oldCount then
    local prefix = mod:GetCostumePrefix(p)
    if prefix then
      mod:UpdateCostumes(p)
    end
    p:GetData().ConsistentTearsCollectibleCount = collectibleCount
  end
end)

mod:AddCallback(ModCallbacks.MC_POST_NEW_ROOM, function(_)
  local players = mod.GetPlayers()
  for _, p in pairs(players) do
    local prefix = mod:GetCostumePrefix(p)
    if prefix then
      mod:UpdateCostumes(p)
    end
  end
end)

mod:AddCallback(ModCallbacks.MC_USE_ITEM, function(_, item, rng, p)
  local prefix = mod:GetCostumePrefix(p)
  if prefix then
    if mod.ItemCostumes[item] then mod:ScheduleForUpdate(function() mod:ReplaceItemCostume(p, item) end) end
    if item == CollectibleType.COLLECTIBLE_CLICKER then
      mod:UpdateCostumes(p)
    end
  end
end)

mod:AddCallback(ModCallbacks.MC_USE_PILL, function(_, pill, p, useFlags, pillColor)
  local isHorsePill = (pillColor & PillColor.PILL_GIANT_FLAG) == PillColor.PILL_GIANT_FLAG
  local prefix = mod:GetCostumePrefix(p)
  if prefix then
    local null = mod.PillToNull[pill]
    if null and mod.NullCostumes[null] then
      mod:ScheduleForUpdate(function() mod:ReplaceItemCostume(p, null, true) end)
    end
  end
end)