local TR_Manager = require("resurrected_modpack.manager")
TR_Manager:Init()

require("resurrected_modpack.shaders")

require("resurrected_modpack.modcompat.ANM2")
require("resurrected_modpack.modcompat.VS_screen")
require("resurrected_modpack.modcompat.disable_mods")
require("resurrected_modpack.modcompat.custom_boss_weight_fix")
require("resurrected_modpack.modcompat.boss_icons")

-- require("resurrected_modpack.enums")

-- require("resurrected_modpack.tools.custom_callbacks")
-- require("resurrected_modpack.tools.global_variables")
-- require("resurrected_modpack.tools.global_functions")
-- require("resurrected_modpack.tools.console_commands")

TR_Manager:LoadMod("resurrected_modpack.graphics.swaggy_mushrooms")
TR_Manager:LoadMod("resurrected_modpack.graphics.unique_gurgling_sprite")
TR_Manager:LoadMod("resurrected_modpack.graphics.red_ending_chest")
TR_Manager:LoadMod("resurrected_modpack.graphics.custom_corpse_chest")
TR_Manager:LoadMod("resurrected_modpack.graphics.improved_backdrops_void_overlay")
TR_Manager:LoadMod("resurrected_modpack.graphics.improved_backdrops")
TR_Manager:LoadMod("resurrected_modpack.graphics.beast_laugh_on_damage")
TR_Manager:LoadMod("resurrected_modpack.graphics.gehenna_visual_tweaks")
TR_Manager:LoadMod("resurrected_modpack.graphics.crawlspaces_rebuilt")
TR_Manager:LoadMod("resurrected_modpack.graphics.antibirth_hornfel_trail")
TR_Manager:LoadMod("resurrected_modpack.graphics.forgotten_got_real_chain")
TR_Manager:LoadMod("resurrected_modpack.graphics.bygone_over_bb")
TR_Manager:LoadMod("resurrected_modpack.graphics.keeper_coin_tears")
TR_Manager:LoadMod("resurrected_modpack.graphics.better_lasers_for_fallen_angels")
TR_Manager:LoadMod("resurrected_modpack.graphics.missing_costumes")
TR_Manager:LoadMod("resurrected_modpack.graphics.item_pedestal_overhaul")
TR_Manager:LoadMod("resurrected_modpack.graphics.missing_tears_gfx")
TR_Manager:LoadMod("resurrected_modpack.graphics.better_donation_machines")
TR_Manager:LoadMod("resurrected_modpack.graphics.falling_isaac")
TR_Manager:LoadMod("resurrected_modpack.graphics.card_resprites")
TR_Manager:LoadMod("resurrected_modpack.graphics.gurdvd")
TR_Manager:LoadMod("resurrected_modpack.graphics.achievement_portraits")
TR_Manager:LoadMod("resurrected_modpack.graphics.head_of_the_keeper_costume")
TR_Manager:LoadMod("resurrected_modpack.graphics.unique_progress_bar_icon")
TR_Manager:LoadMod("resurrected_modpack.graphics.animated_costumes")
TR_Manager:LoadMod("resurrected_modpack.graphics.reflective_downpour_mirror")
TR_Manager:LoadMod("resurrected_modpack.graphics.unique_hazards")
TR_Manager:LoadMod("resurrected_modpack.graphics.unique_stage_variants")
TR_Manager:LoadMod("resurrected_modpack.graphics.better_boss_rush_backdrop")
TR_Manager:LoadMod("resurrected_modpack.graphics.voiding_effect")
TR_Manager:LoadMod("resurrected_modpack.graphics.tainted_lost_death_animation")
TR_Manager:LoadMod("resurrected_modpack.graphics.fancy_boss_hp_bar")
TR_Manager:LoadMod("resurrected_modpack.graphics.extra_npcs")
TR_Manager:LoadMod("resurrected_modpack.graphics.shop_fly")
TR_Manager:LoadMod("resurrected_modpack.graphics.item_spawn_animation")
TR_Manager:LoadMod("resurrected_modpack.graphics.extra_scared_hearts")
-- TR_Manager:LoadMod("resurrected_modpack.graphics.ready_to_fire_up")
TR_Manager:LoadMod("resurrected_modpack.graphics.giant_books")
TR_Manager:LoadMod("resurrected_modpack.graphics.unique_delirium_ending_chest")
TR_Manager:LoadMod("resurrected_modpack.graphics.items_drop_on_death")
TR_Manager:LoadMod("resurrected_modpack.graphics.sheol_trapdoor")
TR_Manager:LoadMod("resurrected_modpack.graphics.necromancer_costume")
TR_Manager:LoadMod("resurrected_modpack.graphics.animated_pickup_counter")
TR_Manager:LoadMod("resurrected_modpack.graphics.mystery_egg_stages")

TR_Manager:LoadMod("resurrected_modpack.tweaks.lamb_intro_invincibility")
TR_Manager:LoadMod("resurrected_modpack.tweaks.chests_before_mother")
-- TR_Manager:LoadMod("resurrected_modpack.tweaks.rare_chests")
TR_Manager:LoadMod("resurrected_modpack.tweaks.unique_delirium_door")
TR_Manager:LoadMod("resurrected_modpack.tweaks.fallen_gabriel_spawns_imps")
TR_Manager:LoadMod("resurrected_modpack.tweaks.bombable_devil_statue")
TR_Manager:LoadMod("resurrected_modpack.tweaks.amazing_chest_ahead")
TR_Manager:LoadMod("resurrected_modpack.tweaks.seven_floors_of_bad_luck")
TR_Manager:LoadMod("resurrected_modpack.tweaks.regret_pedestals")
TR_Manager:LoadMod("resurrected_modpack.tweaks.better_fires")
TR_Manager:LoadMod("resurrected_modpack.tweaks.double_spiked_rocks")
TR_Manager:LoadMod("resurrected_modpack.tweaks.glitched_breakfast")
TR_Manager:LoadMod("resurrected_modpack.tweaks.enemy_blood_donations")
TR_Manager:LoadMod("resurrected_modpack.tweaks.centered_fallen_angel")
TR_Manager:LoadMod("resurrected_modpack.tweaks.expanded_blue_womb")
TR_Manager:LoadMod("resurrected_modpack.tweaks.centered_fallen_angel")
TR_Manager:LoadMod("resurrected_modpack.tweaks.expanded_blue_womb")
TR_Manager:LoadMod("resurrected_modpack.tweaks.unlockable_utero")
TR_Manager:LoadMod("resurrected_modpack.tweaks.pickups_removal")
TR_Manager:LoadMod("resurrected_modpack.tweaks.minisaac_for_mom")
TR_Manager:LoadMod("resurrected_modpack.tweaks.hush_itempool")
TR_Manager:LoadMod("resurrected_modpack.tweaks.giant_props")
TR_Manager:LoadMod("resurrected_modpack.tweaks.giga_bomb_synergies")
TR_Manager:LoadMod("resurrected_modpack.tweaks.enhancement_chamber")

TR_Manager:LoadMod("resurrected_modpack.qol.hanging_dream_catcher")
TR_Manager:LoadMod("resurrected_modpack.qol.hud_toggle")
TR_Manager:LoadMod("resurrected_modpack.qol.items_renamed")
TR_Manager:LoadMod("resurrected_modpack.qol.coin_flip")
TR_Manager:LoadMod("resurrected_modpack.qol.ff_fortunes")
TR_Manager:LoadMod("resurrected_modpack.qol.melee_range_fix")
TR_Manager:LoadMod("resurrected_modpack.qol.the_stars_align")
TR_Manager:LoadMod("resurrected_modpack.qol.low_firerate_chargebar")
TR_Manager:LoadMod("resurrected_modpack.qol.soul_4_me")
TR_Manager:LoadMod("resurrected_modpack.qol.options_reminder")
TR_Manager:LoadMod("resurrected_modpack.qol.accurate_devil_beggars")
TR_Manager:LoadMod("resurrected_modpack.qol.clearer_hidden_enemies")
TR_Manager:LoadMod("resurrected_modpack.qol.book_of_the_dead_reminder")

TR_Manager:LoadMod("resurrected_modpack.shaders.hotter_mines")
TR_Manager:LoadMod("resurrected_modpack.shaders.critical_damage")
TR_Manager:LoadMod("resurrected_modpack.shaders.realistic_black_hole")

TR_Manager:LoadMod("resurrected_modpack.sounds.shepard_tone")
TR_Manager:LoadMod("resurrected_modpack.sounds.bell_chime_for_good_items")
TR_Manager:LoadMod("resurrected_modpack.sounds.character_hit_sounds")
TR_Manager:LoadMod("resurrected_modpack.sounds.rag_mega_sounds_like_rag_man")

TR_Manager:LoadMod("resurrected_modpack.music.unique_mega_satan_music")