local mod = require("resurrected_modpack.mod_reference")

mod.Enums = {}

CallbackPriority.EARLIER = -2^52
CallbackPriority.LATER = 2^52
CallbackPriority.MAX = -1/0
CallbackPriority.MIN = 1/0

if not REPENTOGON then
    Achievement = Achievement or {}
    Achievement.RED_KEY = 415
    Achievement.WOODEN_CHEST = 609
end

if not REPENTOGON then
    BossType = BossType or {}
    BossType.MONSTRO = 1
    BossType.LARRY_JR = 2
    BossType.CHUB = 3
    BossType.GURDY = 4
    BossType.MONSTRO_II = 5
    BossType.MOM = 6
    BossType.SCOLEX = 7
    BossType.MOMS_HEART = 8
    BossType.FAMINE = 9
    BossType.PESTILENCE = 10
    BossType.WAR = 11
    BossType.DEATH = 12
    BossType.DUKE_OF_FLIES = 13
    BossType.PEEP = 14
    BossType.LOKI = 15
    BossType.BLASTOCYST = 16
    BossType.GEMINI = 17
    BossType.FISTULA = 18
    BossType.GISH = 19
    BossType.STEVEN = 20
    BossType.CHAD = 21
    BossType.HEADLESS_HORSEMAN = 22
    BossType.FALLEN = 23
    BossType.SATAN = 24
    BossType.IT_LIVES = 25
    BossType.HOLLOW = 26
    BossType.CARRION_QUEEN = 27
    BossType.GURDY_JR = 28
    BossType.HUSK = 29
    BossType.BLOAT = 30
    BossType.LOKII = 31
    BossType.BLIGHTED_OVUM = 32
    BossType.TERATOMA = 33
    BossType.WIDOW = 34
    BossType.MASK_OF_INFAMY = 35
    BossType.WRETCHED = 36
    BossType.PIN = 37
    BossType.CONQUEST = 38
    BossType.ISAAC = 39
    BossType.BLUE_BABY = 40
    BossType.DADDY_LONG_LEGS = 41
    BossType.TRIACHNID = 42
    BossType.HAUNT = 43
    BossType.DINGLE = 44
    BossType.MEGA_MAW = 45
    BossType.GATE = 46
    BossType.MEGA_FATTY = 47
    BossType.CAGE = 48
    BossType.MEGA_GURDY = 49
    BossType.DARK_ONE = 50
    BossType.ADVERSARY = 51
    BossType.POLYCEPHALUS = 52
    BossType.MR_FRED = 53
    BossType.LAMB = 54
    BossType.MEGA_SATAN = 55
    BossType.GURGLINGS = 56
    BossType.STAIN = 57
    BossType.BROWNIE = 58
    BossType.FORSAKEN = 59
    BossType.LITTLE_HORN = 60
    BossType.RAG_MAN = 61
    BossType.ULTRA_GREED = 62
    BossType.HUSH = 63
    BossType.DANGLE = 64
    BossType.TURDLINGS = 65
    BossType.FRAIL = 66
    BossType.RAG_MEGA = 67
    BossType.SISTERS_VIS = 68
    BossType.BIG_HORN = 69
    BossType.DELIRIUM = 70
    BossType.ULTRA_GREEDIER = 71
    BossType.MATRIARCH = 72
    BossType.PILE = 73
    BossType.REAP_CREEP = 74
    BossType.LIL_BLUB = 75
    BossType.WORMWOOD = 76
    BossType.RAINMAKER = 77
    BossType.VISAGE = 78
    BossType.SIREN = 79
    BossType.TUFF_TWINS = 80
    BossType.HERETIC = 81
    BossType.HORNFEL = 82
    BossType.GREAT_GIDEON = 83
    BossType.BABY_PLUM = 84
    BossType.SCOURGE = 85
    BossType.CHIMERA = 86
    BossType.ROTGUT = 87
    BossType.MOTHER = 88
    BossType.MAUS_MOM = 89
    BossType.MAUS_HEART = 90
    BossType.MIN_MIN = 91
    BossType.CLOG = 92
    BossType.SINGE = 93
    BossType.BUMBINO = 94
    BossType.COLOSTOMIA = 95
    BossType.SHELL = 96
    BossType.TURDLET = 97
    BossType.RAGLICH = 98
    BossType.DOGMA = 99
    BossType.THE_BEAST = 100
    BossType.HORNY_BOYS = 101
    BossType.CLUTCH = 102
    BossType.CADAVRA = 103
end

mod.Enums.DebugMode = {
    ENTITY_POSITIONS = 1,
    SHOW_GRID = 2,
    INFINITE_HP = 3,
    HIGH_DAMAGE = 4,
    ROOM_INFO = 5,
    SHOW_HITBOX = 6,
    SHOW_DAMAGE_VALUES = 7,
    INFINITE_CHARGE = 8,
    HIGH_LUCK = 9,
    QUICK_KILL = 10,
    SHOW_GRID_INFO = 11,
    PLAYER_INFO = 12,
    SHOW_GRID_COLLISION = 13,
    SHOW_LUA_MEMORY_USAGE = 14
}

mod.Enums.InitSubType = { -- Only works for the game's internal morphing algorithm (executed prior to MC_POST_INIT firing)
    RANDOM = 0,
    NO_MORPH = 1
}