return {
    IconScale = 1.0,
    RightMargin = 4,
    TopPosition = 50,
    BottomPosition = 80,
    ItemListColumns = 2,
    JacobEsauItemListColumns = 1,
    ShowLemegetonItems = true,
    IconOpacity = 0.4,
    UpdateInterval = 1,
    ScrollDownKey = Keyboard.KEY_PAGE_DOWN,
    ScrollUpKey = Keyboard.KEY_PAGE_UP,
    ScrollHomeKey = Keyboard.KEY_HOME,
    ScrollEndKey = Keyboard.KEY_END,
    CombineTrinkets = true,
    CombineCollectibles = false,
    LoggingEnabled = false,
}
